server:
  port: 8081

spring:
  application:
    name: loop-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
startup:
  info:
    enabled: true
    project-name: TradingSpringCloud Loop
    frontend: none
    h2: false
    api-docs: false
    probe: true
    extra-paths: /api/v1/trust
