server:
  port: 8080

spring:
  application:
    name: gateway

trading:
  services:
    loop-url: http://localhost:8081
    order-url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
